export const locations = [
    'PÅ STRANDEN',
    'PÅ FLYGPLATSEN',
    'PÅ TEATERN',
    'PÅ RESTAURANGEN',
    'PÅ SJUKHUSET',
    'I BIBLIOTEKET',
    'I SKOLAN',
    'VID SKRIVBORDET',
    'I PARKEN',
    'PÅ BION',
    'PÅ MUSÉET',
    'PÅ LEKPLATSEN',
    'I TRÄDGÅRDEN',
    'I KYRKAN',
    'I KÖKET',
    'I LEKSAKSAFFÄREN',
    'I SKOGEN',
    'PÅ APOTEKET',
    'I FABRIKEN',
    'PÅ SLOTTET',
    'PÅ DJURPARKEN',
    'PÅ FRISÖRSALONGEN',
    'PÅ CAFÉET',
    'PÅ MACKEN',
    'HEMMA',
    'PÅ BUSSEN',
    'I TUNNELBANAN',
    'PÅ EN Ö',
    'PÅ BILTVÄTTEN',
    'VID HAMNEN',
    'PÅ SKIDBACKEN',
    'PÅ GOLFBANAN',
    'VID SJÖN',
    'I BOKAFFÄREN',
    'I VÄXTHUSET',
    'PÅ TÅGSTATIONEN',
    'I GARAGET',
    'UPPE I BIG BEN',
    'I POOLEN',
    'PÅ ISBANAN',
    'I KONDITORIET',
    'PÅ POSTEN',
    'PÅ SECONDHAND BUTIK',
    'I ORTEN',
    'PÅ HIKINGLEDEN',
    'I FÄNGELSET',
    'I FÖRRÅDET',
    'PÅ MOUNT EVEREST',
    'PÅ SKOGSSTIGEN',
    'PÅ KARUSELLEN',
    'PÅ KRETA',
    'I GAMLA STAN',
    'PÅ HÄSTGÅRDEN',
    'PÅ REHAB',
    'PÅ VINGÅRDEN',
    'VID TULLEN',
    'I FJÄLLSTUGAN',
    'I HIMLEN',
    'PÅ KRYSSNINGSFARTYG',
    'I SOPORNA',
    'I EN SARDINBURK',
    'I JULTOMTENS SÄCK',
    'I GRAVEN',
    'I EN KAFFEKOPP',
    'I SNUSDOSAN',
    'I TOALETEN',
    'I HELVETET',
    'PÅ SEMESTER',
    'PÅ EN SKATEBOARDRAMP',
    'PÅ CYKELN',
    'I LIVSMEDELS BUTIKEN',
    'I EN KRUKA',
    'I DISKHON',
    'I MIKROVÅGSUGNEN',
    'I KYLSKÅPET',
    'I EN POPCORNMASKIN',
    'I TVÄTTMASKINEN',
    'I EN LUFTBALLONG',
    'I EN GODISAFFÄR',
    'PÅ EN KAMEL',
    'I EN GUMMIBÅT',
    'I EN ASTRONAUTDRÄKT',
    'I EN SNÖGLOB',
    'PÅ EN RAKET',
    'PÅ EN RYMDSTATION',
    'PÅ EN ENHÖRNING',
    'I EN PÖL',
    'I EN REGNBÅGE',
    'PÅ EN RULLTRAPPA',
    'I EN CHOKLADFABRIK',
    'PÅ EN ELSCOOTER',
    'I PÅ EN TRAMPOLIN',
    'I EN IGLOO',
    'I EN HAMBURGARE',
    'I EN SOFFA',
    'PÅ EN RYMDRESA',
    'PÅ EN SURFINGBRÄDA',
    'PÅ JULAFTON',
];