export const locations = [
    'På stranden | At the Beach',
    'På flygplatsen | At the Airport',
    'På teatern | At the Theater',
    'På restaurangen | At the Restaurant',
    'På sjukhuset | At the Hospital',
    'I biblioteket | In the Library',
    'I skolan | In the School',
    'I butiken | In the Store',
    'På kaffebaren | At the Coffee Shop',
    'Vid skrivbordet | At the Desk',
    'I parken | In the Park',
    'I biblioteket | In the Library',
    'På bion | At the Cinema',
    'På muséet | At the Museum',
    'I affären | In the Shop',
    'På lekplatsen | At the Playground',
    'På stadion | At the Stadium',
    'Vid havet | By the Sea',
    'I trädgården | In the Garden',
    'I kyrkan | In the Church',
    'I köket | In the Kitchen',
    'I leksaksaffären | In the Toy Store',
    'I skogen | In the Forest',
    'I laget | In the Team',
    'På konserthuset | At the Concert Hall',
    'På stranden | At the Beach',
    'På apoteket | At the Pharmacy',
    'I fabriken | In the Factory',
    'På slottet | At the Castle',
    'På djurparken | At the Zoo',
    'På frisörsalongen | At the Hair Salon',
    'På vägen | On the Road',
    'Vid floden | By the River',
    'Vid tunnelbanestationen | At the Subway Station',
    'I affären | In the Shop',
    'På caféet | At the Cafe',
    'I rummet | In the Room',
    'På macken | At the Gas Station',
    'På fjället | On the Mountain',
    'I skogsstugan | In the Forest Cabin',
    'På gården | On the Farm',
    'På museet | At the Museum',
    'På fästningen | At the Fortress',
    'Vid bryggan | By the Pier',
    'På vägen | On the Path',
    'I huset | In the House',
    'På bussen | On the Bus',
    'I staden | In the City',
    'I vinterlandet | In the Winterland',
    'I tunnelbanan | On the Subway',
    'På ön | On the Island',
    'Vid havsbaden | At the Seaside',
    'I bageriet | In the Bakery',
    'På stortorget | At the Main Square',
    'I förrådet | In the Storage',
    'Vid biltvätten | At the Car Wash',
    'Vid hamnen | At the Harbor',
    'I skärgården | In the Archipelago',
    'På skidbacken | On the Ski Slope',
    'Vid utkiken | At the Lookout',
    'På trappan | On the Stairs',
    'På gatan | On the Street',
    'På golfbanan | On the golf course',
    'Vid sjön | By the lake',
    'I bokaffären | In the book store',
    'I växthuset | In the greenhouse',
    'På tågstationen | At the train station',
    'I garaget | In the garage',
    'Uppe i Big Ben | Up in Big Ben',
    'I poolen | In the pool',
    'På isbanan | On the ice rink',
    'På biografen | At the movie theater',
    'I konditoriet | At the pastry shop',
    'På ICA | At ICA',
    'På posten | At the post office',
    'På secondhand butik | At the thrift shop',
    'I orten | In the hood',
    'På hikingleden | On a hiking trail',
    'I fängelset | In prison',
    'I förrådet | In the storage room',
    'På Mount Everest | On Mount Everest',
    'På skogsstigen | On the forest trail',
    'På karusellen | On the carousel',
    'På Kreta | In Crete',
    'I Gamla Stan | At Gamla Stan',
    'På hästgården | On the horse farm',
    'På rehab | At rehab',
    'På vingården | At the vineyard',
    'Vid tullen | At the border control',
    'I fjällstugan | At the nountain cabin',
    'I himlen | In heaven',
];
