export const locations = [
    'på stranden - at the beach',
    'på flygplatsen - at the airport',
    'på teatern - at the theater',
    'på restaurangen - at the restaurant',
    'på sjukhuset - at the hospital',
    'i biblioteket - in the library',
    'i skolan - in the school',
    'vid skrivbordet - at the desk',
    'i parken - in the park',
    'på bion - at the cinema',
    'på muséet - at the museum',
    'på lekplatsen - at the playground',
    'i trädgården - in the garden',
    'i kyrkan - in the church',
    'i köket - in the kitchen',
    'i leksaksaffären - in the toy store',
    'i skogen - in the forest',
    'på apoteket - at the pharmacy',
    'i fabriken - in the factory',
    'på slottet - at the castle',
    'på djurparken - at the zoo',
    'på frisörsalongen - at the barber shop',
    'på caféet - at the café',
    'på macken - at the gas station',
    'hemma - at home',
    'på bussen - on the bus',
    'i tunnelbanan - on the subway',
    'på ön - on the island',
    'på biltvätten - in the car wash',
    'vid hamnen - at the harbor',
    'på skidbacken - on the ski slope',
    'på golfbanan - on the golf course',
    'vid sjön - by the lake',
    'i bokaffären - in the book store',
    'i växthuset - in the greenhouse',
    'på tågstationen - at the train station',
    'i garaget - in the garage',
    'uppe i big ben - up in big ben',
    'i poolen - in the pool',
    'på isbanan - on the ice rink',
    'i konditoriet - at the pastry shop',
    'på posten - at the post office',
    'på secondhand butik - at the thrift shop',
    'i orten - in the hood',
    'på hikingleden - on a hiking trail',
    'i fängelset - in prison',
    'i förrådet - in the storage room',
    'på mount everest - on mount everest',
    'på skogsstigen - on the forest trail',
    'på karusellen - on the carousel',
    'på kreta - in crete',
    'i gamla stan - at gamla stan',
    'på hästgården - on the horse farm',
    'på rehab - at rehab',
    'på vingården - at the vineyard',
    'vid tullen - at the border control',
    'i fjällstugan - at the mountain cabin',
    'i himlen - in heaven',
    'på kryssningsfartyg - in a cruise ship',
    'i soporna - in the garbage',
    'i en sardinburk - in a sardine can',
    'i jultomtens säck - in santa\'s bag',
    'i graven - in the grave',
    'i en kaffekopp - in a coffee cup',
    'i snusdosan - in the snus box',
    'i toaleten - in the toilet',
    'i helvetet - in hell',
    'på semester - on vacation',
    'på en skateboardramp - on a skateboard ramp',
    'på cykeln - on the bicycle',
    'i livsmedels butiken - at the food store',
    'i en kruka - in a flower pot',
    'i diskhon - in the sink',
    'i mikrovågsugnen - in the microwave',
    'i kylskåpet - in the fridge',
    'i en popcornmaskin - in a popcorn machine',
    'i tvättmaskinen - in the washing machine',
    'i en luftballong - in a hot air balloon',
    'i en godisaffär - in the candy store',
    'på en kamel - on a camel',
    'i en gummibåt - in a rubber boat',
    'i en astronautdräkt - in an astronaut suit',
    'i en snöglob - in a snow globe',
    'på en raket - on a rocket',
    'på en rymdstation - on a space station',
    'på en enhörning - on a unicorn',
    'i en pöl - in a puddle',
    'i en regnbåge - in a rainbow',
    'på en rulltrappa - on an escalator',
    'i en chokladfabrik - in a chocolate factory',
    'på en elscooter - on a e-scooter',
    'i på en trampolin - on a trampoline',
    'i en igloo - in an igloo',
    'i en hamburgare - in a hamburger',
    'i en soffa - in a couch',
    'på en rymdresa - on a space journey',
    'på en surfingbräda - on a surfboard',
    'på julafton - on christmas eve',
];
