export const locations = [
    'På stranden - At the beach',
    'På flygplatsen - At the airport',
    'På teatern - At the theater',
    'På restaurangen - At the restaurant',
    'På sjukhuset - At the hospital',
    'I biblioteket - In the library',
    'I skolan - In the school',
    'Vid skrivbordet - At the desk',
    'I parken - In the park',
    'På bion - At the cinema',
    'På muséet - At the museum',
    'På lekplatsen - At the playground',
    'I trädgården - In the garden',
    'I kyrkan - In the church',
    'I köket - In the kitchen',
    'I leksaksaffären - In the toy store',
    'I skogen - In the forest',
    'På apoteket - At the pharmacy',
    'I fabriken - In the factory',
    'På slottet - At the castle',
    'På djurparken - At the zoo',
    'På frisörsalongen - At the barber shop',
    'På caféet - At the café',
    'På macken - At the gas station',
    'Hemma - At home',
    'På bussen - On the bus',
    'I tunnelbanan - On the subway',
    'På ön - On the island',
    'På biltvätten - In the car wash',
    'Vid hamnen - At the harbor',
    'På skidbacken - On the ski slope',
    'På golfbanan - On the golf course',
    'Vid sjön - By the lake',
    'I bokaffären - In the book store',
    'I växthuset - In the greenhouse',
    'På tågstationen - At the train station',
    'I garaget - In the garage',
    'Uppe i Big Ben - Up in Big Ben',
    'I poolen - In the pool',
    'På isbanan - On the ice rink',
    'I konditoriet - At the pastry shop',
    'På posten - At the post office',
    'På secondhand butik - At the thrift shop',
    'I orten - In the hood',
    'På hikingleden - On a hiking trail',
    'I fängelset - In prison',
    'I förrådet - In the storage room',
    'På Mount Everest - On Mount Everest',
    'På skogsstigen - On the forest trail',
    'På karusellen - On the carousel',
    'På Kreta - In Crete',
    'I Gamla Stan - At Gamla Stan',
    'På hästgården - On the horse farm',
    'På rehab - At rehab',
    'På vingården - At the vineyard',
    'Vid tullen - At the border control',
    'I fjällstugan - At the mountain cabin',
    'I himlen - In heaven',
    'På kryssningsfartyg - In a cruise ship',
    'I soporna - In the garbage',
    'I en sardinburk - In a sardine can',
    'I jultomtens säck - In Santa\'s bag',
    'I graven - In the grave',
    'I en kaffekopp - In a coffee cup',
    'I snusdosan - In the snus box',
    'I toaleten - In the toilet',
    'I helvetet - In hell',
    'På semester - On vacation',
    'På en skateboardramp - On a skateboard ramp',
    'På cykeln - On the bicycle',
    'I livsmedels butiken - At the food store',
    'I en kruka - In a flower pot',
    'I diskhon - In the sink',
    'I mikrovågsugnen - In the microwave',
    'I kylskåpet - In the fridge',
    'I en popcornmaskin - In a popcorn machine',
    'I tvättmaskinen - In the washing machine',
    'I en luftballong - In a hot air balloon',
    'I en godisaffär - In the candy store',
    'På en kamel - On a camel',
    'I en gummibåt - In a rubber boat',
    'I en astronautdräkt - In an astronaut suit',
    'I en snöglob - In a snow globe',
    'På en raket - On a rocket',
    'På en rymdstation - On a space station',
    'I en dinosaurie - In a dinosaur',
    'På en enhörning - On a unicorn',
    'I en pöl - In a puddle',
    'I en regnbåge - In a rainbow',
    'På en rulltrappa - On an escalator',
    'I en chokladfabrik - In a chocolate factory',
    'På en elscooter - On a e-scooter',
    'I på en trampolin - On a trampoline',
    'I en igloo - In an igloo',
    'I en hamburgare - In a hamburger',
    'I en soffa - In a couch',
    'På en rymdresa - On a space journey',
    'På en surfingbräda - On a surfboard',
    'På julafton - On Christmas Eve',
];
